apiVersion: apps/v1
kind: Deployment
metadata:
  name: movie-tracker-api
  labels:
    app: movie-tracker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: movie-tracker
  template:
    metadata:
      labels:
        app: movie-tracker
    spec:
      containers:
      - name: main-container
        image: localhost:32000/movie-tracker
        imagePullPolicy: Always
        env:
          - name: "MONGODB_CONNECTION_STRING"
            value: "mongodb://root:IaKGcQRQeP@my-mongo-mongodb.default.svc.cluster.local"
        ports:
          - containerPort: 8080
            name: http-web
---
apiVersion: v1
kind: Service
metadata:
  name: movie-tracker-service
  annotations:
    prometheus.io/port: "8080"
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
spec:
  type: NodePort
  selector:
    app: movie-tracker
  ports:
  - name: http
    protocol: TCP
    port: 8080
    targetPort: http-web
